name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Compose
      run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml
    - name: Docker-Compose Up
      run: docker-compose up -d
    - name: Slight Pause
      run: sleep 10
    - name: Run tests
      run: docker-compose exec cronitex mix do compile --warnings-as-errors --umbrella, coveralls.json
    - name: Upload Coverage
      run: bash <(curl -s https://codecov.io/bash)
